name: Test with Ubuntu, Miniconda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python from Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
    - name: Install conda dependencies
      run: |
        # printenv
        conda update -n base -c defaults conda
        conda config --set always_yes true --set changeps1 true
        conda config --add channels conda-forge
        conda install python=${{ matrix.python-version }}
        conda install numpy=>1.21 scipy=>1.8 matplotlib=>3.4 pillow scikit-learn pandas h5py imageio sqlalchemy psutil pyyaml
        conda install psycopg2-binary numdifftools emcee cython pyparsing pytest pytest-cov coverage
        #conda install tomopy
        conda install wxpython pymatgen pycifrw
    - name: Install xraylarch and other dependencies with pip
      run: |
        conda info -a
        conda list
        pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils fabio silx imageio
        pip install .
    - name: Run test suite
      run: |
        cd tests
        python -m pytest
